#
# Proxy Stack
#

proxy:
    image: tutum/haproxy:0.2.1
    links:
     - wordpress
     - directory
    ports:
     - <%=httpPort%>:<%=httpPort%>
     - <%=httpsPort%>:<%=httpsPort%>
    environment:
     - DEFAULT_SSL_CERT=<%=sslcert%>

#
# LDAP Stack
#

directory:
    image: shasoco/fusiondirectory:1.0
    restart: always
    links:
     - ldap
    environment:
     - "VIRTUAL_HOST=http://directory.<%=httpHost%>,https://directory.<%=httpsHost%>"
     - SSL_CERT=<%-sslcert%>
     - LDAP_ORGANIZATION=<%=name%>
     - LDAP_DOMAIN=<%=name%>
     - LDAP_PASSWORD=<%=rootpassword%>
     - FUSIONDIRECTORY_PASSWORD=<%=adminpassword%>

ldap:
    image: shasoco/openldap:2.4
    restart: always
    volumes_from:
     - ldapdata
    environment:
     - LDAP_ORGANIZATION=<%=name%>
     - LDAP_DOMAIN=<%=name%>
     - LDAP_PASSWORD=<%=rootpassword%>

ldapdata:
    image: busybox
    command: echo ready
    volumes:
     - /var/lib/ldap/

#
# Wordpress Stack:
#
# - wordpress
# - mysql
# - hectane
#

wordpress:
  image: wordpress:4.3
  links:
    - wordpressdb:db
    - wordpressmail:mail
  volumes:
    - ./wordpress-php.ini:/usr/local/etc/php/php.ini
  volumes_from:
    - wordpressdata
  environment:
    - "VIRTUAL_HOST=http://www.<%=httpHost%>,https://www.<%=httpsHost%>,http://<%=httpHost%>,https://<%=httpsHost%>"
    - SSL_CERT=<%=sslcert%>
    - WORDPRESS_DB_HOST=db
    - WORDPRESS_DB_NAME=wordpress
    - WORDPRESS_DB_USER=admin
    - WORDPRESS_DB_PASSWORD=<%=adminpassword%>
  restart: always

wordpressdb:
  image: mysql:5.6
  volumes_from:
    - wordpressdbdata
  environment:
    - MYSQL_ROOT_PASSWORD=<%=rootpassword%>
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=<%=adminpassword%>
    - MYSQL_DATABASE=wordpress
  restart: always

wordpressmail:
  image: hectane/hectane:0.2.1
  volumes:
    - /data
  environment:
    - DISABLE_SSL_VERIFICATION=1
  restart: always

wordpressdbdata:
  image: busybox
  command: echo ready
  volumes:
    - /var/lib/mysql

wordpressdata:
  image: busybox
  command: echo ready
  volumes:
    - /var/www/html

#
#
#

