#
# Proxy Stack
#

proxy:
    image: tutum/haproxy:0.2.1
    links:
     - wordpress:www
    ports:
     - <%-httpPort%>:<%-httpPort%>
     - <%-httpsPort%>:<%-httpsPort%>
    environment:
     - DEFAULT_SSL_CERT=<%-sslcert%>

#
# Wordpress Stack:
#
# - wordpress
# - mysql
# - hectane
#

wordpress:
  image: wordpress:4.3
  links:
    - wordpressdb:db
    - wordpressmail:mail
  volumes:
    - ./wordpress-php.ini:/usr/local/etc/php/php.ini
  volumes_from:
    - wordpressdata
  environment:
    - VIRTUAL_HOST=http://www.<%-name%><% if(httpPort!='80') print(':'+httpPort); %>,https://www.<%-name%><% if(httpsPort!='443') print(':'+httpsPort); %>
    - SSL_CERT=<%-sslcert%>
    - WORDPRESS_DB_HOST=db
    - WORDPRESS_DB_NAME=wordpress
    - WORDPRESS_DB_USER=admin
    - WORDPRESS_DB_PASSWORD=<%-adminpassword%>
  restart: always

wordpressdb:
  image: mysql:5.6
  volumes_from:
    - wordpressdbdata
  environment:
    - MYSQL_ROOT_PASSWORD=<%-rootpassword%>
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=<%-adminpassword%>
    - MYSQL_DATABASE=wordpress
  restart: always

wordpressmail:
  image: hectane/hectane:0.2.1
  volumes:
    - /data
  environment:
    - DISABLE_SSL_VERIFICATION=1
  restart: always

wordpressdbdata:
  image: busybox
  command: echo ready
  volumes:
    - /var/lib/mysql

wordpressdata:
  image: busybox
  command: echo ready
  volumes:
    - /var/www/html

#
#
#

